sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
  - '8'
before_script:
  - npm prune
script:
  - git --version
  - node .
  - $(npm bin)/if-node-version ">=8" ./next-update-travis.sh
  - $(npm bin)/if-node-version ">=8" npm test
after_success:
  - TRAVIS_JOB_NUMBER=WORKAROUND.1 $(npm bin)/if-node-version ">=8" npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
