sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: true
node_js:
  - '6'
  - '8'
before_script:
  - npm prune
script:
  - git --version
  - node .
  - node src/tracked-source-files.js
  - $(npm bin)/if-node-version ">=8" npm test
after_success:
  - $(npm bin)/if-node-version ">=8" npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
