sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '4'
  - '6'
before_script:
  - npm prune
script:
  - git --version
  - node .
  - $(npm bin)/if-node-version ">=6" ./next-update-travis.sh
  - TRAVIS_JOB_NUMBER=WORKAROUND.1 $(npm bin)/if-node-version ">=6" DEBUG=snap-shot-core $(npm bin)/if-node-version ">=6" npm test
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
